version: '2.1'

services:
  blockbridge-simulator-converged:
    image: ${REGISTRY}blockbridge/simulator:latest
    container_name: bbsim-converged
    volumes:
      - bb_data:/bb/data
    ports:
      - "80:80"
      - "443:443"
      - "3260:3260"
    ulimits:
      msgqueue: 128000000
    privileged: true

volumes:
  bb_data:
