version: '2'

services:
  blockbridge-simulator-converged:
    image: blockbridge/simulator:latest
    container_name: bbsim-converged
    networks:
      discovery:
        aliases:
          - bbsim-mn
          - bbsim-converged
    ports:
      - "80:80"
      - "443:443"
      - "3260:3260"
      - "20400:20400"
    ulimits:
      msgqueue: 128000000
    privileged: true
    environment:
      BB_SIM_IP: ${BB_SIM_IP}
    labels:
      com.docker.swarm.constraints: '["node==*${BB_SIM_NODE}*"]'

networks:
  discovery:
    driver: overlay
